server:
  compression:
     enabled: true
     mime-types: application/json,application/xml,text/html,text/xml,text/plain
  server-header: concur-connector

management:
  endpoints:
    web.base-path: /

# Needs to be configured by their own enterprise concur client id and client secret.
concur:
  client-id: dummy-client-id
  client-secret: dummy-client-secret
  oauth-instance-url: http://us-impl.api.concursolutions.com