server:
  compression:
     enabled: true
     mime-types: application/json,application/xml,text/html,text/xml,text/plain
  server-header: hub-salesforce-connector
  port: 9090

connector:
  hasTestAuth: true

management:
  endpoints:
    web.base-path: /

security:
  oauth2:
    resource:
      jwt:
        key-uri: https://herocard.vmwareidentity.com/SAAS/API/1.0/REST/auth/token?attribute=publicKey&format=pem